spring:
  application:
    name: application



  security:
    oauth2:



      client:
        provider:
          keycloak: # Add the provider name here to match with the registration
            issuer-uri: http://localhost:7080/realms/cloudEnv
        registration:
          keycloak:
            provider: keycloak
            authorization-grant-type: authorization_code
            client-id: IoT-Streaming-Cloud-REST-API
            client-secret: qj6SvBcnnUuuqZYOxKDAEWXnLqA9UW4w
            scope: openid
            redirect-uri: http://localhost:8084/login/oauth2/code/keycloak



server:
  port: 8084


logging:
  level:
    org:
      springframework:
        security: DEBUG


